export const UPDATE_AUTH = 'UPDATE_AUTH'
export const UPDATE_LOAD_APP = 'UPDATE_LOAD_APP'
export const UPDATE_LOGGED_IN = 'UPDATE_LOGGED_IN'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const LOGIN = 'LOGIN'


export const UPDATE_BACKDROP = 'UPDATE_BACKDROP'


export const UPDATE_WAITLOADER = 'UPDATE_WAITLOADER'